MODEL:
  NAME: 'detector_mobilenet'
  IMAGE_SIZE: [224, 224, 3]
  NUM_CLASSES: 20
  BASE_MODEL:
    ALPHA: 1.0
    CHECKPOINT: '/home/feaf-seat-1/Documents/nesvera/detectors/base_weights/mobilenet_224_a1-0.pth.tar'
  
TRAIN:
  MAX_EPOCHS: 2400
  BATCH_SIZE: 8
  WORKERS: 8
  PRINT_FREQ: 100               # print each x batches
  OPTIMIZER:
    OPTIMIZER: 'SGD'
    LEARNING_RATE: 0.002
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
  REPRODUCIBILITY:
    REPRODUCIBILITY: False
    SEED: 0
  LR_SCHEDULER:
    LR_SCHEDULER: True
    MIN_LR: 0.00001
    MAX_LR: 0.002
    LR_DECAY: 0.00              # e.g. 0.2 = decrease 20% the max_lr by cycle
    CYCLE: 200                   # number of epochs for each cycle
    CYCLE_MULT: 0.00            # e.g. 0.2 = increase 20% the cycle length 

TEST:
  BATCH_SIZE: 32

EXP_DIR: './experiments/'
LOG_DIR: './experiments/'
RESUME_CHECKPOINT: 'BEST_detector_mobilenet.pth.tar'
#RESUME_CHECKPOINT: 'detector_mobilenet.pth.tar'

# lr_new = lr * ( 1 - lr_decay )^(cycle)
# cycle_new = cycle * (1 + cycle_mult)^(cycle)
