MODEL:
  NAME: 'detector_vgg_16'
  IMAGE_SIZE: [300, 300, 3]
  NUM_CLASSES: 20
  BASE_MODEL:
    CHECKPOINT: None
  
TRAIN:
  MAX_EPOCHS: 2400
  BATCH_SIZE: 8
  WORKERS: 8
  PRINT_FREQ: 100               # print each x batches
  OPTIMIZER:
    OPTIMIZER: 'SGD'
    LEARNING_RATE: 0.0001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
  REPRODUCIBILITY:
    REPRODUCIBILITY: False
    SEED: 0
  LR_SCHEDULER:
    LR_SCHEDULER: True
    MIN_LR: 0.00005
    MAX_LR: 0.0001
    LR_DECAY: 0.00              # e.g. 0.2 = decrease 20% the max_lr by cycle
    CYCLE: 1200                   # number of epochs for each cycle
    CYCLE_MULT: 0.01            # e.g. 0.2 = increase 20% the cycle length 

TEST:
  BATCH_SIZE: 32

EXP_DIR: './experiments/'
LOG_DIR: './experiments/'
RESUME_CHECKPOINT: 'BEST_detector_mobilenet_dw_224.pth.tar'

# lr_new = lr * ( 1 - lr_decay )^(cycle)
# cycle_new = cycle * (1 + cycle_mult)^(cycle)
